---
apiVersion: v1
kind: Service
metadata:
  name: ergonrh
  namespace: ergonrh
  labels:
    app: ergonrh
spec:
  ports:
    - port: 80
  selector:
    app: ergonrh
    tier: frontend
  type: LoadBalancer
