---
apiVersion: v1
kind: Service
metadata:
  name: ergonrh-hmg
  namespace: techne-hmg
  labels:
    app: ergonrh-hmg
spec:
  ports:
    - port: 80
  selector:
    app: ergonrh-hmg
    tier: frontend
  type: LoadBalancer
